### ISSUE TITLE
Performance Challenges with ordhook

### ISSUE THREAD

**Issue by suatap-alt** [hirosystems/bitcoin-indexer#346]
Hey, I'm wondering if you've run into any speed bumps when indexing tons of Ordinal inscriptions?
Any tips on how to keep things running smoothly when there's a lot going on?

**Comment by rafaelcr** [comment]
hi @suatap-alt , indexing ordinals is a very intense process. I would need to look at your specific setup to give you feedback but right out the gate I would recommend you work on a machine with a fast hard disk and extensive memory. Also, make sure that your bitcoin node is running on a high performance machine that is as close to ordhook as possible in networking terms (or try to run bitcoind in the same machine) because there are a ton of RPC calls that need to be made into it.

**Comment by smcclellan** [comment]
Thank you for filing this -- for any additional questions, please check out the #ordinals channel in [the Stacks Discord](https://stacks.chat/).
